"""Shilp Python SDK - Official Python SDK for the Shilp Vector Database API."""

from shilp.client import Client
from shilp.discovery_client import DiscoveryClient
from shilp.models import (
    # Request models
    AddCollectionRequest,
    InsertRecordRequest,
    IngestRequest,
    SearchRequest,
    UpdateReplicaLSNRequest,
    RegisterReplicaRequest,
    UnRegisterReplicaRequest,
    FileReaderOptions,
    DebugGetEmbeddingsRequest,
    EnableMetadataStoreRequest,
    SettingsUpdateRequest,
    # Response models
    GenericResponse,
    HealthResponse,
    ListCollectionsResponse,
    Collection,
    MetadataSupportInfo,
    InsertRecordResponse,
    IngestResponse,
    ListIngestionSourcesResponse,
    SearchResponse,
    ListStorageResponse,
    ReadDocumentResponse,
    ListEmbeddingModelsResponse,
    OplogStatusResponse,
    GetOplogResponse,
    UpdateReplicaLSNResponse,
    GetCollectionDataResponse,
    CollectionDataRecord,
    GetCollectionSchemaResponse,
    CollectionSchema,
    Attribute,
    AttributeType,
    CategorySchema,
    CategoryValue,
    ListNLIVerticalsResponse,
    VerticalInfo,
    EnableMetadataStoreResponse,
    GetSettingsResponse,
    SettingsAvailableProvidersResponse,
    # Debug models
    DebugDistanceData,
    DebugDistanceResponse,
    DebugNodeInfoResponse,
    DebugLevelsResponse,
    DebugNodesAtLevelResponse,
    DebugReferenceNodeResponse,
    DebugGetEmbeddingsResponse,
    # Enums and types
    AttrType,
    FilterOp,
    SortOrder,
    StorageBackendType,
    IndexType,
    IngestSourceType,
    FuzzyAlgo,
    OpType,
    SyncStatus,
    ReplicaType,
    # Filter and Sort expressions
    FilterExpression,
    CompoundFilter,
    SortExpression,
    CompoundSort,
    # Discovery and Replica models
    Replica,
    Status,
    ProxyStats,
    DiscoveryStats,
    VectorCreateConfig,
    VectorSearchConfig,
    Settings,
    SettingsAuth,
    APIAuthConfig,
    ProviderArgumentValue,
    SettingsIntegration,
    SettingsProviderArguments,
    SettingsProviderType,
    SettingsProviderInfo,
    SettingsAvailableProvidersData,
)

__version__ = "0.14.0"
__all__ = [
    "Client",
    "DiscoveryClient",
    # Request models
    "AddCollectionRequest",
    "InsertRecordRequest",
    "IngestRequest",
    "SearchRequest",
    "UpdateReplicaLSNRequest",
    "RegisterReplicaRequest",
    "UnRegisterReplicaRequest",
    "FileReaderOptions",
    "DebugGetEmbeddingsRequest",
    "EnableMetadataStoreRequest",
    "SettingsUpdateRequest",
    # Response models
    "GenericResponse",
    "HealthResponse",
    "ListCollectionsResponse",
    "Collection",
    "MetadataSupportInfo",
    "InsertRecordResponse",
    "IngestResponse",
    "ListIngestionSourcesResponse",
    "SearchResponse",
    "ListStorageResponse",
    "ReadDocumentResponse",
    "ListEmbeddingModelsResponse",
    "OplogStatusResponse",
    "GetOplogResponse",
    "UpdateReplicaLSNResponse",
    "GetCollectionDataResponse",
    "CollectionDataRecord",
    "GetCollectionSchemaResponse",
    "CollectionSchema",
    "Attribute",
    "AttributeType",
    "CategorySchema",
    "CategoryValue",
    "ListNLIVerticalsResponse",
    "VerticalInfo",
    "EnableMetadataStoreResponse",
    "GetSettingsResponse",
    "SettingsAvailableProvidersResponse",
    # Debug models
    "DebugDistanceData",
    "DebugDistanceResponse",
    "DebugNodeInfoResponse",
    "DebugLevelsResponse",
    "DebugNodesAtLevelResponse",
    "DebugReferenceNodeResponse",
    "DebugGetEmbeddingsResponse",
    # Enums and types
    "AttrType",
    "FilterOp",
    "SortOrder",
    "StorageBackendType",
    "IndexType",
    "IngestSourceType",
    "FuzzyAlgo",
    "OpType",
    "SyncStatus",
    "ReplicaType",
    # Filter and Sort expressions
    "FilterExpression",
    "CompoundFilter",
    "SortExpression",
    "CompoundSort",
    # Discovery and Replica models
    "Replica",
    "Status",
    "ProxyStats",
    "DiscoveryStats",
    "VectorSearchConfig",
    "VectorCreateConfig",
    "Settings",
    "SettingsAuth",
    "APIAuthConfig",
    "ProviderArgumentValue",
    "SettingsIntegration",
    "SettingsProviderArguments",
    "SettingsProviderType",
    "SettingsProviderInfo",
    "SettingsAvailableProvidersData",
]
